### ISSUE TITLE
Bureau Contractors: project - download the Reclamations dams

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WaDE-Side-Projects#10]
https://github.com/WSWCWaterDataExchange/WaDE-Side-Projects/tree/main/20230406%20Bureau%20Contractors

**Reclamation shared this dataset which has the "operating entities" of dams which are equivalent to contractors** 
https://www.arcgis.com/apps/mapviewer/index.html?layers=1df76b35789f448094cec79c53c42555

**Comment by rwjam** [comment]
We need to update all Water right data with the new "Reclamation Contractor" value.  This will include running all of the following water right scripts and uploading for...

AK
AZ
CA
CO
ID
KS
MN
MT
ND
NE
NM
NV
OK
OR
SD
TX
UT
WA
WY

**Comment by rwjam** [comment]
Updated entire water right database to include new "Reclamation Contractor" OwnerClassificationCV.

**Note**: Results are differing a little from the projected results of the [20230406 Bureau Contractors](https://github.com/WSWCWaterDataExchange/WaDE-Side-Projects/tree/main/20230406%20Bureau%20Contractors) wade side project, with the side project estimating more water rights with a OwnerClassificationCV = Reclamation Contractor (see below img / attached BC_db and side project comparison.xlsx file).  I suspect this is due how we are [assigning OwnerClassificationCV with a hierarchy value](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/5_CustomFunctions/OwnerClassification), which we did not account for within the side project (i.e., water rights we identified to have an OwnerClassificationCV = Reclamation Contractor within the side project, are being assigned a different OwnerClassificationCV value within the WaDE db due to the overwriting hierarchy approach we implment).


![Image](https://github.com/WSWCWaterDataExchange/WaDE-Side-Projects/assets/17555073/e5d1f931-b490-4685-85f2-cfdcfd674b43)


[BC_db and side project comparison.xlsx](https://github.com/WSWCWaterDataExchange/WaDE-Side-Projects/files/13731240/BC_db.and.side.project.comparison.xlsx)

**Comment by amabdallah** [comment]
Thanks for the hard work on this tenuous issue. Would you update Maptiler for Staging? I see the water rights now are there in the db and it would help me to see them fully in WestDAAT for testing purposes. I think this is great for now, it will take some time to dig through.  

https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoPZgHYFMIGEA2BDAzjglgGb4DGWALvnIjjANogBKyJ2AthVYgARrXkQsJcnCgBdADQh8OAHIYAJvgBi%2BDOVQBBYfgBuyGISwYcyAL5SOABxigAXnDhsAMsn0YYAVgB0ARk8AHABsAEwhAJy%2BAOwADDEhUZFS2JTkAK4KBtAAzOHeudmFydQA5vjpmTAAtL4xAd6eMdkRZmZAA

![image](https://github.com/WSWCWaterDataExchange/WaDE-Side-Projects/assets/3268971/f7354382-c7d4-4f02-a988-5f5907b0b414)

**Comment by rwjam** [comment]
updated maptiler
